### ISSUE TITLE
[Component] TextField: Add scale factor to corner radius

### ISSUE THREAD

**Issue by LouisBorleeAdevinta** [adevinta/spark-ios#1009]
When the dynamic size changes, the corner radius do not scale with it atm

For example, a corner radius of 4px on a 40px component will be 10% whereas for a 80px it will only be 5% (less rounded)

![Image](https://github.com/adevinta/spark-ios/assets/124776620/25682a39-8ba2-409e-8104-76acbe852e60)
![Image](https://github.com/adevinta/spark-ios/assets/124776620/5df83508-3b51-46a3-8308-d42082f20f3f)

Here you can see one with the scaling (the most rounded one) and one without

**Comment by elisa-hery** [comment]
Nice ! Result here (with max size) :

_**before :**_ 



<picture>
  <img alt="specs" src="https://github.com/adevinta/spark-ios/assets/142396647/ad8788b4-bbd1-4e8a-847c-313be9cce89d" width="200px">
</picture>


**_after :_** 

<picture>
  <img alt="specs" src="https://github.com/adevinta/spark-ios/assets/142396647/f13a372b-a5eb-4a14-9c89-a4d2c4aaa901" width="200px">
</picture>
