### ISSUE TITLE
Typography

### ISSUE THREAD

**Issue by turolopezsanabria** [adevinta/spark-ios#139]
TBD

**Comment by LouisBorleeAdevinta** [comment]
Typography on Polaris seems to be crashing on some devices
We made a hotfix on last week's release, reverted the code using Spark Typography, added logs and re-published it
But one commit was not merged on the master branch and so on this version, the revert has not been merged and crashes still occurs
We still have no idea why, the fix doesn't work, logs don't appear
We are adding the revert on the master and republishing this week's release

**Comment by LouisBorleeAdevinta** [comment]
Update June 6th
Discussed with KA and implemented another solution, tests have been planned for next week's release on the abuse report view with a killswitch if things go bad
