### ISSUE TITLE
[Component] RadioButton UIKit / Optional Label in Selection States

### ISSUE THREAD

**Issue by michael-zimmermann** [adevinta/spark-ios#177]
At the moment, the states "error", "warning" and "success" need to have a sub-label assigned to them.
This sub-label is optional.

**Comment by michael-zimmermann** [comment]
See https://spark-3unbow1c0-spark-team.vercel.app/?path=/docs/components-radiogroup--docs#using-a-formfield

**Comment by turolopezsanabria** [comment]
Can I close this one?
