### ISSUE TITLE
[Components] Radio-button integration SwiftUI

### ISSUE THREAD

**Issue by thomas-leguellec** [adevinta/spark-ios#32]

**Comment by thomas-leguellec** [comment]
Add the finalized specs

**Comment by thomas-leguellec** [comment]
In this ticket, we handle the basis, groupment and alignment: https://zeroheight.com/1186e1705/v/latest/p/98058f-radio-button/b/700a17

The specificites will be done in another ticket: https://github.com/orgs/adevinta/projects/4/views/10?pane=issue&itemId=24374407

**Comment by LouisBorleeAdevinta** [comment]
- [ ] SwiftUI
- [ ] UIKit
