### ISSUE TITLE
[Fix] Checkbox: unselected color

### ISSUE THREAD

**Issue by robergro** [adevinta/spark-ios#329]
Currently when checkbox items are not selected, the color of the square corresponding to the main color (blue for Adevinta, orange for Leboncoin...) but it should be gray
![Simulator Screenshot - iPhone 14 Pro - 2023-08-22 at 10 20 21](https://github.com/adevinta/spark-ios/assets/6044208/78201f3e-9efd-4c3f-a9d1-b65c148169b3)

**Comment by thomas-leguellec** [comment]
- integrating the new design
- code refactoring
- fixing tests
- fixing demo project

**Comment by michael-zimmermann** [comment]
Fixed with https://github.com/adevinta/spark-ios/issues/473
