### ISSUE TITLE
[Component] Switch: Create Native SwiftUI component

### ISSUE THREAD

**Issue by robergro** [adevinta/spark-ios#428]
Create the native SwiftUI component

- [x] View
- [x] Snapshot testing

**Comment by robergro** [comment]
PR: 
- https://github.com/adevinta/spark-ios/pull/445
- https://github.com/adevinta/spark-ios/pull/455

**Comment by elisa-hery** [comment]
Hey @robergro ; after visual and functional testing, I noticed 1 problem : for activated/disabled switch with image, the icon doesn't seem to have the right color. 

What I see : 
<img src="https://github.com/adevinta/spark-ios/assets/142396647/d1842bb9-b8e3-47da-85de-1c7dbc56da48" alt="isolated" width="200"/>

What it should be according to [figma](https://www.figma.com/file/NsGfE3UnbhEyAPpVf3B60P/Spark-Components?type=design&node-id=14%3A3852&mode=design&t=8ptC8Tzj6trgiEAT-1) : 

<img src="https://github.com/adevinta/spark-ios/assets/142396647/3558fe1d-33e5-4b17-a39d-888800524f3c" alt="isolated" width="150"/>

**Comment by robergro** [comment]
OoOo ! Thank you !
It's good now 

https://github.com/adevinta/spark-ios/assets/6044208/f62799af-5860-4269-9610-427b68dc75f3

**Comment by robergro** [comment]
The PR to resolve this bug is here :
https://github.com/adevinta/spark-ios/pull/463
