### ISSUE TITLE
[Fix] Switch: Implement optionnal text

### ISSUE THREAD

**Issue by robergro** [adevinta/spark-ios#430]
The text is mandatory currently, we must update the UIKit component to have an optional text

**Comment by robergro** [comment]
PR: 
- https://github.com/adevinta/spark-ios/pull/445
- https://github.com/adevinta/spark-ios/pull/455

**Comment by elisa-hery** [comment]
Hey @robergro , only for UI kit I noticed a desynchro between toggles when you do this specific journey : 
- when arriving on the page, turn the demo switch off
- Then turn the "is On" switch on --> then it's desynchronising 

https://github.com/adevinta/spark-ios/assets/142396647/fc260bc6-ebc8-4b0e-8e9c-032685d6f29a

**Comment by robergro** [comment]
I reproduced it this morning too. After some investigation, the problem is just on our demo.
We need to simplify the UIKit component demo and fix some troubles like this...
Sorry ...!

**Comment by elisa-hery** [comment]
A ticket is dedicated to this bug --> https://github.com/adevinta/spark/issues/1496
