### ISSUE TITLE
[Component] Chip SwiftUI Variant

### ISSUE THREAD

**Issue by michael-zimmermann** [adevinta/spark-ios#457]
Add the native SwiftUI implementation of the chip.

Not included in this are:
- the selected state
- the changes to the surface intent

**Comment by michael-zimmermann** [comment]
The PR has been merged.
Please test on `main`

**Comment by michael-zimmermann** [comment]
The design changes of the chip are not included in this PR. There is a follow PR for the design changes https://github.com/adevinta/spark-ios/pull/495.
In this PR the native SwiftUI component is implemented using the old design.

Chip groups are not implemented in iOS. This would need to be a separate component.

**Comment by elisa-hery** [comment]
All my comment above will be handled in https://github.com/adevinta/spark-ios/pull/495, I'm closing it
