### ISSUE TITLE
[Component] Tab: UIKit Fix double tap

### ISSUE THREAD

**Issue by michael-zimmermann** [adevinta/spark-ios#480]
When a tab is tapped, the delegate and action are triggered twide

**Comment by michael-zimmermann** [comment]
The PR has been merged.
Please test on `main`

**Comment by elisa-hery** [comment]
@michael-zimmermann : cannot really test it, but non regression done ✅

**Comment by elisa-hery** [comment]
Topic to discuss with the iOS team : 
- how to test "technical resilience" (eg : is a call triggered only once ?)
- should we test it on the demo app with a console in it ?
