### ISSUE TITLE
[Fix][Synchronicity] Remove subscriptions from all components

### ISSUE THREAD

**Issue by LouisBorleeAdevinta** [adevinta/spark-ios#507]
Status:
Using subscriptions is not working properly when the main thred is in use and so we need to change our ways in every component
Related Slack thread (contains videos) https://adevinta.slack.com/archives/C04QCSQGQUX/p1693835378103049
```[tasklist]
### Split tickets
- [ ] https://github.com/adevinta/spark-ios/issues/497
- [ ] https://github.com/adevinta/spark-ios/issues/498
- [ ] https://github.com/adevinta/spark-ios/issues/499
- [ ] https://github.com/adevinta/spark-ios/issues/500
- [ ] https://github.com/adevinta/spark-ios/issues/501
- [ ] https://github.com/adevinta/spark-ios/issues/502
- [ ] https://github.com/adevinta/spark-ios/issues/503
- [ ] https://github.com/adevinta/spark-ios/issues/504
- [ ] https://github.com/adevinta/spark-ios/issues/505
- [ ] https://github.com/adevinta/spark-ios/issues/506
```

**Comment by robergro** [comment]
The first thing to do before update all components is to check if with the new Scheduler, there is no more this problem.
The PR is [here](https://github.com/adevinta/spark-ios/pull/513).
