### ISSUE TITLE
[Bug] Tab (SwiftUI). Tabs flash to full size and back when setting badge in Demo.

### ISSUE THREAD

**Issue by michael-zimmermann** [adevinta/spark-ios#509]
Given: The user is on the SparkCore demo and has the swiftUI tab component open
When: I enable the "show badge" option
Then: The tabs shortly flash to full size and back.

**Comment by elisa-hery** [comment]
Vidéo of the bug : 

https://github.com/adevinta/spark-ios/assets/142396647/7cdf525c-d05e-4ea7-a778-e2e0ad86b7c5
