### ISSUE TITLE
[Fix] Switch: spacing when there is no text

### ISSUE THREAD

**Issue by robergro** [adevinta/spark-ios#568]
On SwiftUI, if we remove the text (set text to nil), the space between the toggle and the text is still here BUT it shouldn't !

**Comment by elisa-hery** [comment]
Bugfix tested, I just noticed 1 thing : when you switch from right to left alignement behaviour is weird (see video below). Is it related to demo app or sthg could be improved ?

https://github.com/adevinta/spark-ios/assets/142396647/845d7c2d-6c91-4e41-b502-70b59b3368a4

**Comment by elisa-hery** [comment]
new ticket for this alignement problem --> https://github.com/adevinta/spark-ios/issues/584

**Comment by elisa-hery** [comment]
I'm moving this one to done @robergro !
