### ISSUE TITLE
[Fix] Badge: Component doesn't seem to size properly if it is not initialized with a value.

### ISSUE THREAD

**Issue by michael-zimmermann** [adevinta/spark-ios#572]
When the Badge is integrated in Polaris, sizing errors, and coloring errors were seen, when the badge wasn't initialized with an initial value.

Wrong:
![Image](https://github.com/adevinta/spark-ios/assets/128726463/707f7b6c-6c7f-49b4-b26d-c29097d51bde)

Expected:
![Image](https://github.com/adevinta/spark-ios/assets/128726463/db310bf9-cfb7-4e4d-9c3d-567147f4251d)

**Comment by michael-zimmermann** [comment]
To test: Please use the main branch and test on the demo app. The error was on the UIKit component.
I've updated the demo app, so that changing the text value will set the badge value to nil, when the text is empty.

**Comment by elisa-hery** [comment]
Ok great thanks @michael-zimmermann , it's ok ✅
