### ISSUE TITLE
[Component] Textfield status icon and state

### ISSUE THREAD

**Issue by jacklyn-situmorang** [adevinta/spark-ios#607]
- Implement status icon for alert, success, and error intents
- Implement disabled state

**Comment by elisa-hery** [comment]
Testing informations |  
-- | --
Risk level ? | high (= must be tested by QAA before release)
Does this ticket need to be design reviewed ? | yes
Referent designer : | ?
Spec : | [figma](https://www.figma.com/file/0QchRdipAVuvVoDfTjLrgQ/Spark-Specs-and-Handoff?type=design&node-id=8638-1179&mode=design&t=cE36I8XgPjJA6p7j-0)
Testing checklist : | [gsheet](https://docs.google.com/spreadsheets/d/14qVXQeGgD2jALstn83DxeCiKU86JD-jDNffg7YsAHr8/edit#gid=781937415)
UATs : | [confluence](https://confluence.ets.mpi-internal.com/display/SPAR/Textlink)
configurator : | [confluence](https://confluence.ets.mpi-internal.com/display/SPAR/Textlink/#Textlink-demo-app-configurator)
