### ISSUE TITLE
[Fix] Bad performance due to layoutIfNeeded

### ISSUE THREAD

**Issue by robergro** [adevinta/spark-ios#610]
One Polaris developper found an issue:
_"since upgrade to SparkCore 0.7.9, we have hangs issue on TagUIView due to layoutIfNeeded triggered by the change at init of classified cards in order to disable dynamic font"_

The goal of this ticket is to replace when it's possible the layoutIfNeeded.

![Image](https://github.com/adevinta/spark-ios/assets/6044208/d18332b2-dc5e-4746-af79-1d38a5355ac4)

**Comment by elisa-hery** [comment]
@robergro I did a quick check on `Switch`, `Tag`, `Icons` --> nothing to say ✅
