### ISSUE TITLE
[Component] Checkbox / Wrong halo color on pressed state

### ISSUE THREAD

**Issue by michael-zimmermann** [adevinta/spark-ios#619]
(UI kit & swift UI) small design issue : on pressing, halo is always grey although it should be the intent's color

**Comment by elisa-hery** [comment]
@aycil-alican it's fixed, let's merge it ✅ 😊 

https://github.com/adevinta/spark-ios/assets/142396647/3ddbea0a-3da9-4cab-b8be-771afb8faa67
