### ISSUE TITLE
[Button] Refactoring: Add common Control management

### ISSUE THREAD

**Issue by robergro** [adevinta/spark-ios#623]
Check the [parent ticket](https://github.com/adevinta/spark-ios/issues/557) to read more informations

**Comment by elisa-hery** [comment]
Clarifications after a call with @robergro  : 
- **goal of this refacto** : allow UI tests for users + prepare the split between IconButton and Button (a next PR will come with the actual split)
- **what's new** : content of the button is now linked to the state (eg : the text can be different between normal and pressed state). **This will allow the toggle IconButton.**
- I will focus the manuel tests on the states (check if all states are still working)

Other informations : 
- only for UI kit (no button in swift UI anyway) 
- in demo app, highlighted = pressed state.

**Comment by elisa-hery** [comment]
I checked button's state and it seems ok ✅
