### ISSUE TITLE
[Component] Rating Display (SwiftUI)

### ISSUE THREAD

**Issue by michael-zimmermann** [adevinta/spark-ios#667]

**Comment by elisa-hery** [comment]
@michael-zimmermann I tested it (see testing checklist [here](https://docs.google.com/spreadsheets/d/1ImANjP4zthfNZkHf5BDH8qO_g5OVG5fn0YiUJPexjCg/edit#gid=896120767)) and it's all good ✅ 
Please note that I cannot test limit values (like 1.24 & 1.25) with demo app so developers have to test them.
