### ISSUE TITLE
[Component] Rating Input SwiftUI

### ISSUE THREAD

**Issue by michael-zimmermann** [adevinta/spark-ios#672]
Create the rating input component for SwiftUI

**Comment by elisa-hery** [comment]
Testing checklist : https://docs.google.com/spreadsheets/d/1ImANjP4zthfNZkHf5BDH8qO_g5OVG5fn0YiUJPexjCg/edit#gid=1906944309

**Comment by elisa-hery** [comment]
@michael-zimmermann :
❌ when changing dynamic types, input rating bugs and we have to kill the app (it's not the case for input rating UI kit)

(detailed results [here](https://docs.google.com/spreadsheets/d/1ImANjP4zthfNZkHf5BDH8qO_g5OVG5fn0YiUJPexjCg/edit#gid=1906944309))

**Comment by michael-zimmermann** [comment]
I've fixed the issue with the dynamic sizing changes

**Comment by elisa-hery** [comment]
@michael-zimmermann perfect ✅  

I think we now need a quick design review, maybe with @JeremiasUX ?
(The pressed state appears briefly everytime we click on rating, I'd like to check if it's ok ⬇️ )

https://github.com/adevinta/spark-ios/assets/142396647/ded3cad4-43dd-486c-9788-7f5d932f76c1

**Comment by JeremiasUX** [comment]
Yes, I can take a look.
I just check other components like the **RadioButton** and its the same behavior, not sure if we can do something against that.

If I change the theme in the test app, the spacing changes, is that something we should take a look at?

**Comment by michael-zimmermann** [comment]
Having a pressed state in iOS is a normal user interaction behavior. For iOS we use the defined "hovered" state as the "pressed" state, since there is no hover state on the phone.
The spacing is defined by the theme, so the fact that it changes, shows that the theme switch works correctly.

**Comment by JeremiasUX** [comment]
Approved from my side. 

@elisa-hery anything to add from your side?

**Comment by elisa-hery** [comment]
@michael-zimmermann : I know about pressed state, I just noticed that for swift UI pressed state appears very stealthily and gives the impression that it's "blinking" (while it doesn't for UI kit). 
But if it's ok for @JeremiasUX, no problem ! 
It's validated on my side ! ✅
