### ISSUE TITLE
[Fix] RadioButton SwiftUI use environment disabled state.

### ISSUE THREAD

**Issue by michael-zimmermann** [adevinta/spark-ios#690]
The swiftui component should use the environment variable "isEnabled" to detect is enabled/disabled state.

**Comment by michael-zimmermann** [comment]
Already merged to main

**Comment by elisa-hery** [comment]
@michael-zimmermann  can I test this one ? on demo app we can only use `radioButton Group`, not single radio button. 
Anyway, as written in https://github.com/adevinta/spark-ios/issues/696, everything is good for RadioButton Group, so i guess it can be moved to RFP as well !
