### ISSUE TITLE
[Fix] RadioButtonGroup: use environment variable to detect disabled state

### ISSUE THREAD

**Issue by michael-zimmermann** [adevinta/spark-ios#696]

**Comment by elisa-hery** [comment]
Explanations from @michael-zimmermann : 
> It's not a real bug, it's just how we implemented some details of the components.
> We used an own view modifier function "disabled()" to let the user be able to set the disabled state. But in swiftUI there is > a general view modifier "disabled()" which would be better to use, to avoid confusion for the user.

About the risk : 
> I think that the only danger is, that previous a component could have been disabled, but it wasn't visible to the user.
> Now it should always be visible to the user.

**conclusion for QA --> radioButton Group (swift UI) is a critical component so it should be tested by me**

**Comment by michael-zimmermann** [comment]
merged to main, so it would need to be tested on main.

**Comment by elisa-hery** [comment]
@michael-zimmermann, I checked it, everything is fine ✅  I'm moving it to done
