### ISSUE TITLE
[Fix] Tab: Use environment variable to set disabled state

### ISSUE THREAD

**Issue by michael-zimmermann** [adevinta/spark-ios#698]

**Comment by michael-zimmermann** [comment]
Need to be tested in main

**Comment by elisa-hery** [comment]
@michael-zimmermann IDK if it's related to your PR but I've noticed a weird behavior on tabs for swift UI : the pressed state is not consistent. Sometimes pressed state remains active whether it should not, and we can remove it by clicking again on the tab. See video below ⬇️ 

https://github.com/adevinta/spark-ios/assets/142396647/32df40d4-de33-4a31-b913-d79306636dac

**Comment by michael-zimmermann** [comment]
No this is a different issue.
Fixed here https://github.com/orgs/adevinta/projects/4/views/19?pane=issue&itemId=48868669
