### ISSUE TITLE
[Fix] Checkbox: Use environment variable to set disabled state

### ISSUE THREAD

**Issue by michael-zimmermann** [adevinta/spark-ios#707]

**Comment by michael-zimmermann** [comment]
Merged to main.

We used to have modifiers for enabling/disabling the component directly on the component.
But in SwiftUI, disable works on a whole block of multiple components.
The effect was, that the component was disabled, but didn't reflect this in the color change.

**Comment by elisa-hery** [comment]
validated ✅
