### ISSUE TITLE
[Bug] Tab (SwiftUI) Doesn't scale correctly when dynamic sizes change

### ISSUE THREAD

**Issue by michael-zimmermann** [adevinta/spark-ios#717]

**Comment by michael-zimmermann** [comment]
This has not been merged to main yet and is on branch `717-but-tab-swiftui-doesnt-scale-correctly-when-dynamic-sizes-change`

**Comment by elisa-hery** [comment]
There is a visual bug after scaling (it disappears when I rotate the screen) : 

https://github.com/adevinta/spark-ios/assets/142396647/ab5bd187-07de-4e11-bdb2-bb6538b36c8f

**Comment by michael-zimmermann** [comment]
I've opened another ticket for this:
https://github.com/adevinta/spark-ios/issues/746
