### ISSUE TITLE
[Checkbox] Use isChanged modifier in ButtonStyle (SwiftUI)

### ISSUE THREAD

**Issue by michael-zimmermann** [adevinta/spark-ios#721]

**Comment by michael-zimmermann** [comment]
Needs to be tested on main.
Only a technical issue, I'm not sure if it really needs to be tested.

**Comment by elisa-hery** [comment]
@michael-zimmermann I just noticed something weird : 
GIVEN a single checkbox
WHEN the checkbox is indeterminate,
THEN I cannot check/uncheck it


https://github.com/adevinta/spark-ios/assets/142396647/38a8d129-07ff-4879-a2c0-a973f747d5a4

**Comment by elisa-hery** [comment]
@michael-zimmermann 's answer : 

> AFAIK, the intermediate state should not be able to be selected, and doens't make sense for a single checkbox. This is a state when a checkbox has sub items, and if all of them are selected, the the intermediate state should also be selected, if none of them are selected, then the checkbox is not selected, and if just some of them are selected, then the intermediate state is shown on the parent.  I don't know of any use cases for the intermediate state, because AFAIK, a checkbox cannot have subitems, or the states will have to be managed by the users.
