### ISSUE TITLE
[Component] Tab Fix layout issues after rotation

### ISSUE THREAD

**Issue by michael-zimmermann** [adevinta/spark-ios#746]

**Comment by michael-zimmermann** [comment]
See ticket https://github.com/adevinta/spark-ios/issues/717

**Comment by elisa-hery** [comment]
Hey @michael-zimmermann , i noticed something weird : 
WHEN

**Comment by michael-zimmermann** [comment]
Hi @elisa-hery,
thanks for finding the very weird case. 
Hopefully, I've fixed it.

**Comment by elisa-hery** [comment]
@michael-zimmermann perfect ✅ 
I'm moving it to RFP

**Comment by elisa-hery** [comment]
PR --> https://github.com/adevinta/spark-ios/pull/796
