### ISSUE TITLE
[Component] Checkbox group doesn't show whole text when it's axis is horizontally

### ISSUE THREAD

**Issue by aycil-alican** [adevinta/spark-ios#756]

**Comment by elisa-hery** [comment]
explanation of the bugs by @aycil-alican : 
- horizontal mode + multiline label --> we cannot see the bottom of the label
- attributed text was not supported

**Comment by aycil-alican** [comment]
All checkbox fixes and changes merged to this branch: https://github.com/adevinta/spark-ios/tree/component/checkbox

**Comment by elisa-hery** [comment]
Ok @aycil-alican it's validated ✅  I'm moving it to RFP
