### ISSUE TITLE
[Component] TextField: UIKit

### ISSUE THREAD

**Issue by LouisBorleeAdevinta** [adevinta/spark-ios#788]

**Comment by elisa-hery** [comment]
<google-sheets-html-origin>

Testing informations |  
-- | --
Risk level ? | high (component MUST be tested by QAA)
Does this ticket need to be design reviewed ? | yes
Referent designer : | ?
Spec : | [figma](https://www.figma.com/file/0QchRdipAVuvVoDfTjLrgQ/Spark-Specs-and-Handoff?type=design&node-id=267%3A8336&mode=design&t=vOmm5vUVSjywxkHM-1)
Testing checklist : | [for visual quality](https://docs.google.com/spreadsheets/d/1qsjX5100A6Hp2bsuhzFKZvliAsgY89iTGzK1e4hXM-8/edit#gid=1131257042) + [classic checklist](https://docs.google.com/spreadsheets/d/1qsjX5100A6Hp2bsuhzFKZvliAsgY89iTGzK1e4hXM-8/edit#gid=1926623587)
UATs : | [confluence](https://confluence.ets.mpi-internal.com/pages/viewpage.action?pageId=163376023) in progress
configurator : | [confluence](https://confluence.ets.mpi-internal.com/pages/viewpage.action?pageId=163376023) in progress

**Comment by elisa-hery** [comment]
This one is validated ✅  I'll move it do RFP
