### ISSUE TITLE
[Component] Checkbox checked image bug

### ISSUE THREAD

**Issue by aycil-alican** [adevinta/spark-ios#803]
- (Error, Success, Alert, Info, Neutral) intent's icon color was changed from onMain to onError, onSuccess, onAlert, onInfo, onNeutral. Snapshots were regenerated.
- When you create checkbox group component first time. There was a small padding on top of component uikit side. It was't seen on demo project. I also fixed this small issue while I was regenerating snaphots.

**Comment by thomas-leguellec** [comment]
![Image](https://github.com/adevinta/spark-ios/assets/123980564/188f9cb8-aa28-48ba-b9ef-a3773ddb8be1)

**Comment by aycil-alican** [comment]
Hello, We fixed checked icon color, but in this image border color is also wrong. It should be outline. I checked "checkbox component" on polaris side with demo project. Borders color seem as expected (outline).  I don't know which page is this but border color problem is from polaris side.

**Comment by aycil-alican** [comment]
- for test branch: component/checkbox_bug_803 
- snapshot tests also regenerated

**Comment by elisa-hery** [comment]
@aycil-alican on demo app we don't have any themes except Adevinta one, so I think won't be able to test that. 
The only think I can check is that Adevinta theme is still ok !

**Comment by aycil-alican** [comment]
@elisa-hery, Hello, you might only test warning intent icon color. It seemed light but with this fix on demo project, It seems dark now

**Comment by elisa-hery** [comment]
@aycil-alican  I checked colors on snapshots & on demo app for single checkbox :
- UI kit light theme : ✅ 
- UI kit dark theme : ✅ 
- Swift UI light theme : ✅ 
- Swift Ui dark theme : ✅ 

ℹ this ticket also include a fix : there was a small space issue on UI kit checkbox group

**Comment by aycil-alican** [comment]
@elisa-hery thank you so much. Should I move this to ready for production column?

**Comment by aycil-alican** [comment]
@elisa-hery Hello, It was revied thanks 🙋‍♂️
