### ISSUE TITLE
[Component] Badge outline color

### ISSUE THREAD

**Issue by Bibisirius** [adevinta/spark-ios#825]
We change the badge outline color by Base/surface 
Spec: [url ](https://spark.adevinta.com/1186e1705/p/8711ec-badge/t/06fc01)

![Image](https://github.com/adevinta/spark-ios/assets/139967199/0e63beff-abce-42ba-abeb-e9415f732172)

**Comment by thomas-leguellec** [comment]
@Bibisirius Can you confirm is it well for iOS and not for Design please?

**Comment by turolopezsanabria** [comment]
The outline color of the badge must be `Base/surface` in all devices.

✅ Figma done
✅ Web done
⁉️ Android
⁉️ iOS
