### ISSUE TITLE
[Component] Formfield

### ISSUE THREAD

**Issue by aycil-alican** [adevinta/spark-ios#858]

**Comment by aycil-alican** [comment]
to test: component/formfield_858, Formfield SwiftUI side was developed according to Figma File.

**Comment by elisa-hery** [comment]
Hey @aycil-alican , based on the [checklist](https://docs.google.com/spreadsheets/d/1DBGCysLrFFcoFXKYpMmQF-Anmt9Qqlc8_kXEzwOLNB4/edit#gid=925235290&range=23:23), here are my remarks : 
1. single checkbox and radio button does not work
2. for checkbox horizontol group we have a weird behavior with space container, see [here](https://docs.google.com/spreadsheets/d/1DBGCysLrFFcoFXKYpMmQF-Anmt9Qqlc8_kXEzwOLNB4/edit#gid=925235290&range=E38)
3. for radio button horizontol group I think spacing is not ok (see [here](https://docs.google.com/spreadsheets/d/1DBGCysLrFFcoFXKYpMmQF-Anmt9Qqlc8_kXEzwOLNB4/edit#gid=925235290&range=H35))
4. last remark : I think we should add left / right alignement for every component (on both UI kit & swift UI) WDYT ?

**Comment by aycil-alican** [comment]
I fixed single checkbox and horizontal checkbox issues. They were related with demo project. Single radio button doesn't have toggle option (select/unselect) as a default. I only added it to show how it seem. Horizontal radio button issue isn't related with Formfield. We should create different task and fix it.

**Comment by elisa-hery** [comment]
Quick summary : everything is fixed except point 3. that will be handled in another ticket.

@adevinta/spark-design it's ready for design review on branch `test_formfield`. The [gsheet](https://docs.google.com/spreadsheets/d/1DBGCysLrFFcoFXKYpMmQF-Anmt9Qqlc8_kXEzwOLNB4/edit#gid=925235290) I used might help you.

**Comment by ChrisDesignOps** [comment]
Holo @aycil-alican, [same as on UiKit](https://github.com/adevinta/spark-ios/issues/782#issuecomment-2098768904), when Title is an `Attribute Text` the Mandatory * change the line-height of the Title

https://github.com/adevinta/spark-ios/assets/81374770/9c23a29c-7370-4c49-97e2-4e25db7479e4

**Comment by ChrisDesignOps** [comment]
✅ Done the review from Design.

Same things [as on UiKit ](https://github.com/adevinta/spark-ios/issues/782#issuecomment-2098794332) about the demo content and not related to the component.

**Comment by aycil-alican** [comment]
Hello, I answered them [here](https://github.com/adevinta/spark-ios/issues/782#issuecomment-2100311643)
