### ISSUE TITLE
[Accessibility] Investigation for checkbox

### ISSUE THREAD

**Issue by thomas-leguellec** [adevinta/spark-ios#860]

**Comment by thomas-leguellec** [comment]
As discussed during the iOS tech meeting the 19 of March, we will do an investigation to do an audit of the work needed for accessibility for the checkbox component (both UIKit and SwiftUI).

After the investigation, we will create another ticket to update the component.

**Comment by aycil-alican** [comment]
I think we might close this ticket, we have already investigated checkbox and created development [ticket.](https://github.com/orgs/adevinta/projects/4/views/19?pane=issue&itemId=58519293)
