### ISSUE TITLE
[Component] Checkbox group disable issue

### ISSUE THREAD

**Issue by aycil-alican** [adevinta/spark-ios#864]
For UIkit checkbox group component: There wasn't a toggle to disable/enable all checkbox group items. It was added to demo project. Now when you change "isEnable" toggle, it should disable/enable all checkbox group items.

For SwiftUI checkbox group component: Consumer might disable checkbox group partially. (Ex: First item disable other items enable). There was a bug to disable partially on demo project. It was fixed. Go checkbox group on demo project , select "Triple Multiline Text" as an Group type. First Item should be disable.

For both of side(UIKit and SwiftUI): If first one item is disable but others enable and consumer wants to disable/enable checkbox group component, in this case disabled item should protect it's state as disabled even though group component is enabled. To test this case, go checkbox group component -> select "Triple Multiline Text" as an Group type -> change all component "isEnabled" toggle.

**Comment by aycil-alican** [comment]
test branch: component/checkbox_bug_864

**Comment by elisa-hery** [comment]
@aycil-alican it's ok ! details : 

### 1. Add a toggle to disable/enable all checkbox group items

**_- UI kit_**
ok ✅  (tested on multiples layouts / with or without title)

**_- Swift UI_**
ok ✅  (tested on multiples layouts / with or without title)

### 2. swift UI / checkbox group partially disabled : ok ✅ 

### 3. disabled item should protect it's state

**_- UI kit_**
ok ✅ 

**_- Swift UI_**
ok ✅
