### ISSUE TITLE
[Accessibility] Fix ProgressBar accessibility

### ISSUE THREAD

**Issue by LouisBorleeAdevinta** [adevinta/spark-ios#878]

**Comment by LouisBorleeAdevinta** [comment]
I've split the ticket in two, it can't have Polaris at the same time because it needs to be released beforehand

**Comment by elisa-hery** [comment]
UI kit : after first test, we notice that "Adjustable" should not be here (Adjustable is for components that user can update)
Back to dev.

![Image](https://github.com/adevinta/spark-ios/assets/142396647/5ce79db3-ab0f-4ba2-8532-b757f12ab6e8)

**Comment by elisa-hery** [comment]
@LouisBorleeAdevinta here are the current a11y values ⬇  do we agree that these are the expected values ? 

### UI kit :

**- single progress bar**


<picture>
  <img alt="specs" src="https://github.com/adevinta/spark-ios/assets/142396647/51e8373f-7a47-4a92-a061-00ebaff86a06" width="500px">
</picture>

<br/><br/>

**- indeterminate progress bar**


<picture>
  <img alt="specs" src="https://github.com/adevinta/spark-ios/assets/142396647/016b803e-db27-4b60-a5fd-298ac48de773" width="500px">
</picture>

<br/><br/>

### swift UI : 


**- single progress bar**

<picture>
  <img alt="specs" src="https://github.com/adevinta/spark-ios/assets/142396647/8bd94a0d-fbc6-48b1-bbcb-6a6edc788532" width="500px">
</picture>

<br/><br/>


**- indeterminate progress bar**

<picture>
  <img alt="specs" src="https://github.com/adevinta/spark-ios/assets/142396647/f8b41196-3e81-4053-bb1c-0c47a7e2c298" width="500px">
</picture>

**Comment by LouisBorleeAdevinta** [comment]
The indeterminate progress bar has no value ("indeterminate")  amd I don't see any other trait they should have so for me it's okay :) 
I hesitated with adding the https://developer.apple.com/documentation/uikit/uiaccessibilitytraits/1620187-updatesfrequently trait but because it has not importance whatsoever for the user, I don't think it's needed and I ended up not adding it

**Comment by elisa-hery** [comment]
Ok so it's validate ! I'm moving it to RFP
