### ISSUE TITLE
[Bug] TextField: Blink when changing intent on a disabled textfield in SwiftUI

### ISSUE THREAD

**Issue by LouisBorleeAdevinta** [adevinta/spark-ios#885]
https://docs.google.com/spreadsheets/d/1yt1YLzNsM_RJK9Ac1u2pcHA5i_kNvFpWvYYdXQhXaCA/edit#gid=139525665&range=5:5

**Comment by LouisBorleeAdevinta** [comment]
https://github.com/adevinta/spark-ios/assets/124776620/83a7da75-ebdb-4b1f-9214-b6d6105445e3

**Comment by LouisBorleeAdevinta** [comment]
It does the same (sometimes) with every change, not just the intent

**Comment by elisa-hery** [comment]
This bug is fixed, it's not blinking anymore ✅ 
tested on iPhone 15 & iPad 10th generation 

https://github.com/adevinta/spark-ios/assets/142396647/e9e4612b-8cb0-4e1e-841c-81ec1f10a985
