### ISSUE TITLE
[Bug] TextField: Correct demo app issues

### ISSUE THREAD

**Issue by LouisBorleeAdevinta** [adevinta/spark-ios#886]
- https://docs.google.com/spreadsheets/d/1yt1YLzNsM_RJK9Ac1u2pcHA5i_kNvFpWvYYdXQhXaCA/edit#gid=139525665&range=2:2
- https://docs.google.com/spreadsheets/d/1yt1YLzNsM_RJK9Ac1u2pcHA5i_kNvFpWvYYdXQhXaCA/edit#gid=139525665&range=6:6
- https://docs.google.com/spreadsheets/d/1yt1YLzNsM_RJK9Ac1u2pcHA5i_kNvFpWvYYdXQhXaCA/edit#gid=139525665&range=7:7

**Comment by elisa-hery** [comment]
This 3 bugs are fixed ✅
