### ISSUE TITLE
[Bug] Button: letter cut

### ISSUE THREAD

**Issue by robergro** [adevinta/spark-ios#911]
The bottom of the character (like **p**, **y**, **g**, ...) is cut when the button size is equals to small

![Image](https://github.com/adevinta/spark-ios/assets/6044208/be89ba1e-b1b8-44bc-8b36-ad960d9b15e7)

**Comment by elisa-hery** [comment]
Sorry for late answer @robergro 
I tested on 2 different devices, on landscape mode, with different shapes / sizes, alignement and variant. 
It's all good for me ✅  🥳
