### ISSUE TITLE
[Bug] Radio button horizontal group bottom space

### ISSUE THREAD

**Issue by aycil-alican** [adevinta/spark-ios#918]
When radio button layout group is horizontal, the space that is under radio button group is too long.
![Image](https://github.com/adevinta/spark-ios/assets/139964419/56be0bb9-3366-462b-bbb4-93b73e369ab4)

**Comment by aycil-alican** [comment]
Hello, I fixed it. Test branch: component/radiobutton_918

**Comment by elisa-hery** [comment]
Fixed ✅ 

**before :**  

<picture>
  <img alt="specs" src="https://github.com/adevinta/spark-ios/assets/142396647/d1fd58cf-a94b-492e-ab41-f3a18dab7c13" width="400px">
</picture>

<br/><br/>

**after :**  

<picture>
  <img alt="specs" src="https://github.com/adevinta/spark-ios/assets/142396647/26f32e36-a465-4df6-95e4-dc4fe81e0584" width="400px">
</picture>
