### ISSUE TITLE
[Component] Checkbox group height issue according alignment

### ISSUE THREAD

**Issue by aycil-alican** [adevinta/spark-ios#939]
if you change checkbox group alignment from left to right and height of checkbox group changes, checkbox group height doesn't update layout immediately.

https://github.com/adevinta/spark-ios/assets/139964419/7b0b065c-779c-4f4b-9e91-b2ec0bc535b0

**Comment by aycil-alican** [comment]
test branch: [component/checkbox_bug](https://github.com/adevinta/spark-ios/tree/component/checkbox_bug)

**Comment by elisa-hery** [comment]
Hey @aycil-alican , 
I'm on branch [component/checkbox_bug](https://github.com/adevinta/spark-ios/tree/component/checkbox_bug) but the bug is still there !

**Comment by aycil-alican** [comment]
@elisa-hery  Hello, Is your branch up to date? I will recheck :+1:

**Comment by elisa-hery** [comment]
Ok it's fixed !
I did a quick non-regression on checkbox (orientation, multiline text, alignement, different icons) : all is ok ✅  
I'm moving it to RFP
