### ISSUE TITLE
[Component] Bottom sheet (SwiftUI)

### ISSUE THREAD

**Issue by michael-zimmermann** [adevinta/spark-ios#943]

**Comment by michael-zimmermann** [comment]
Testable on branch component/bottomsheet.
I'm not sure if there is something to test here really, since we're only providing convenience functions to the standard ios bottom sheet.

**Comment by elisa-hery** [comment]
@michael-zimmermann for swift UI : 
- with rotation on iPhone 15, the version with long text but no scroll view can block navigation. I guess that it's "expected" and that customer should use a scrollview in that case, but at least I think we should be able to dismiss it. WDYT ?





https://github.com/adevinta/spark-ios/assets/142396647/c8ce110b-bae4-43fe-995e-82e32c17ecc3

**Comment by michael-zimmermann** [comment]
> [@michael-zimmermann](https://github.com/michael-zimmermann) for swift UI :
> 
> * with rotation on iPhone 15, the version with long text but no scroll view can block navigation. I guess that it's "expected" and that customer should use a scrollview in that case, but at least I think we should be able to dismiss it. WDYT ?
> 
Yes, this is the responsibility of the user
